import type { Metadata } from "next";
import { Rubik, Caveat} from "next/font/google";
import "./globals.css";

const rubik = Rubik({
   subsets: ["latin"], 
   weight:["300",'400',"800"],
   variable:'--font-rubik'
  });

const caveat = Caveat({
   subsets: ["latin"], 
   weight:['500',"400",'700'],
   variable:'--font-caveat'
  });

export const metadata: Metadata = {
  title: "Dem-Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${caveat.variable}`}>{children}</body>
    </html>
  );
}
